import React, { useState } from 'react';
import { Container, Row, Col, ButtonGroup, Button } from 'react-bootstrap';
import Head from 'next/head'
//import Image from 'next/image'
//import { Inter } from 'next/font/google'
import styles from '../styles/Home.module.css'
//import Header from '@/components/Header'
import { signInWithEmailAndPassword } from 'firebase/auth';
import { signInWithGoogle } from '../lib/auth';
import { auth } from '../lib/firebase';
import { useRouter } from 'next/router' ;
//import styles from '../styles/Login.module.css';
import Image from 'next/image';

const HomePage = () => {
  

  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState(null);
  const router = useRouter();

  const handleLogin = async (e) => {
    e.preventDefault();
    try {
      await signInWithEmailAndPassword(auth, email, password);
      router.push('/dashboard');
    } catch (error) {
      setError(error.message);
    }
  };

  const handleGoogleSignIn = async () => {
    const { user, token, error } = await signInWithGoogle();
    if (user){
    // user is signed 
    router.push('/dashboard');
  } else if (error) {
    // handle with error

  } 
};

  function Home() {

  return (
     <>
       <Head>
       <Image src="/Logo.png" alt="Logo" width={100} height={50} />
            {' '}
        <title>FloralFlow App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

          <Container className={`${styles.main} py-5`}>     
      <Row className="justify-content-center">
        <Col xs={12} md={6} lg={4} className="text-center">
        <Image src="" alt="Logo" width={100} height={50} />
        <h1 className={`${styles.description} mt-3 mb-4`}>Login</h1>
      <p className={`${styles.description} lead mb-4`}>
      Welcome back to FloralFlow!<br></br>
Please enter your email and password to access your account.          </p>
      {error && <p className={styles.error}>{error}</p>}
      <form onSubmit={handleLogin} className={styles.form}>
        <input
          type="email"
          placeholder="Email"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
          className={styles.input}
        />
        <input
          type="password"
          placeholder="Password"
          value={password}
          onChange={(e) => setPassword(e.target.value)}
          className={styles.input}
        />
        <button type="submit" className={styles.input}>Login</button>
        <ButtonGroup>
  <Button href="/login" variant="primary" size="lg">Login</Button>
  <Button href="/register" variant="secondary" size="lg">Register</Button>
</ButtonGroup>       
      
      </form>
    </Col>
     </Row>
        </Container>
</>
  );
};
}

export default HomePage();