import React from 'react';
import { Container, Row, Col, ButtonGroup, Button } from 'react-bootstrap';
import Head from 'next/head'
import Image from 'next/image'
//import { Inter } from 'next/font/google'
import styles from '../styles/Home.module.css'
//import Header from '@/components/Header'

//const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
        <Head>
        <title>FloralFlow App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container className={`${styles.main} py-5`}>     
      <Row className="justify-content-center">
        <Col xs={12} md={6} lg={4} className="text-center">
        {/*   <Logo /> */}
        <h1 className={`${styles.description} mt-3 mb-4`}>Welcome to FloralFlow</h1>
        <p className={`${styles.description} lead mb-4`}>
            FloralFlow is an app that makes inventory management a breeze. Keep track of all your products and orders in one place, and stay on top of your stock levels.
          </p>
          <ButtonGroup>
  <Button href="/login" variant="primary" size="lg">Login</Button>
  <Button href="/register" variant="secondary" size="lg">Register</Button>
</ButtonGroup>        </Col>
      </Row>
      
    </Container>
    </>
  )
}
